OpenShift: Web server on different IP (#779)
* kfish: Fix error when printing error

If we use a self signed `bmc_url` the code fails with a bad error:

```
  File "/usr/lib/python3.13/site-packages/kvirt/kfish/__init__.py", line 54, in get_info
    error(f"Hit issue {e.msg} when accessing url {chassis_url}")
                       ^^^^^
AttributeError: 'URLError' object has no attribute 'msg'
```

The actual error is

```
URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1020)'))
```

This patch adds a generic mechanism to print a text version of the error
when thee `msg` attribute is not present in the exception.

* OpenShift: Web server on different IP

When serving ISO images for baremetal machines on the OpenShift cluster
deployment we were assuming that these were always served on the
`default` network interface, and that's the IP address that was
configured on the BMC of the baremetal server.

This only works if we are running kcli on the same network as the
servers, but that's not the case when we access them through a VPN.

In this patch we add a new configuration option named
`baremetal_web_nic` that allows us to specify the network interface we
want to use to serve the ISO.

The default value will be `default`, to maintain backward compatibility,
but for example we could set it to `tun0` when using the VPN to access
the machines to be provisioned.