openshift: cast openshift version to string (#767)
`tag: 4.17` in the parameter file is assumed to be a float and
causes the following error :

```
File "/usr/lib/python3.12/site-packages/kvirt/cluster/openshift/__init__.py", line 847, in create
    elif int(tag.split('.')[1]) > int(OPENSHIFT_TAG.split('.')[1]):
             ^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'
```

Use `str(tag)` as everywhere else in the `create()` function.

Fixes: 1cf856d0e92f ("openshift: imrprove ci tag detection")

Signed-off-by: Greg Kurz <groug@kaod.org>