Fix the addition of pubkeys with no keys provided
In the last commit a bug was introduced when no `keys` were provided as
parameter. In that case, `keys` would have been `None` and the comparison
`if key not in keys` would fail:

~~~
  File "/usr/lib/python3.10/site-packages/kvirt/common/__init__.py", line 312, in cloudinit
    if key not in keys:
TypeError: argument of type 'NoneType' is not iterable
~~~

Fixes: 6d7dadcbbd1f ("dont put pub keys twice in cloudinit")